version: '3'
services:
  postgres:
    image: postgres:10.1-alpine
    environment:
    - POSTGRES_DB=f1
    - POSTGRES_USER=f1
    - POSTGRES_PASSWORD=f1
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16