CREATE TABLE DIM_CHASSIS 
    ( 
     CHASSIS_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     CONSTRUCTOR VARCHAR (256) , 
     DEVELOP_DATE DATE , 
     INFO VARCHAR (256) 
    ) 
;



COMMENT ON TABLE DIM_CHASSIS IS 'CHASSIS - шасси гоночного автомобиля'
;


COMMENT ON COLUMN DIM_CHASSIS.CHASSIS_ID IS 'CHASSIS_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_CHASSIS.CODE IS 'CODE - кодовое обозначение' 
;

COMMENT ON COLUMN DIM_CHASSIS.CONSTRUCTOR IS 'CONSTRUCTOR - команда (как правило) или организация разработчик шасси' 
;

COMMENT ON COLUMN DIM_CHASSIS.DEVELOP_DATE IS 'DEVELOP_DATE - дата (год) разработки' 
;

COMMENT ON COLUMN DIM_CHASSIS.INFO IS 'INFO - дополнительная информация' 
;


CREATE TABLE DIM_COUNTRY 
    ( 
     COUNTRY_ID INTEGER  NOT NULL , 
     SCD_START DATE  NOT NULL , 
     SCD_END DATE  NOT NULL , 
     SCD_ACTIVE NUMERIC DEFAULT 1  NOT NULL , 
     SCD_VERSION SMALLINT  NOT NULL , 
     NUMERIC_CODE VARCHAR (3)  NOT NULL , 
     ALPHA_CODE VARCHAR (3) , 
     COUNTRY_NAME VARCHAR (256) , 
     SHORT_NAME VARCHAR (256) , 
     UN_REGION_NAME VARCHAR (256) , 
     UN_CONTINENT_NAME VARCHAR (256) 
    ) 
;



COMMENT ON TABLE DIM_COUNTRY IS 'COUNTRY - страна'
;


COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_ID IS 'COUNTRY_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_COUNTRY.SCD_START IS 'SCD_START' 
;

COMMENT ON COLUMN DIM_COUNTRY.SCD_END IS 'SCD_END' 
;

COMMENT ON COLUMN DIM_COUNTRY.SCD_ACTIVE IS 'SCD_ACTIVE' 
;

COMMENT ON COLUMN DIM_COUNTRY.SCD_VERSION IS 'SCD_VERSION' 
;

COMMENT ON COLUMN DIM_COUNTRY.NUMERIC_CODE IS 'NUMERIC_CODE - код страны (3-х значный код по стандарту ISO 3166). Источник: http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=94405;fld=134;dst=4294967295.' 
;

COMMENT ON COLUMN DIM_COUNTRY.ALPHA_CODE IS 'ALPHA_CODE - код страны (3-x буквенный код по стандарту ISO 3166). Источник: http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=94405;fld=134;dst=4294967295.' 
;

COMMENT ON COLUMN DIM_COUNTRY.COUNTRY_NAME IS 'COUNTRY_NAME - название страны. Источник: http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=94405;fld=134;dst=4294967295.' 
;

COMMENT ON COLUMN DIM_COUNTRY.SHORT_NAME IS 'SHORT_NAME - короткое название страны. Источник: http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=94405;fld=134;dst=4294967295.' 
;

COMMENT ON COLUMN DIM_COUNTRY.UN_REGION_NAME IS 'REGION_NAME - регион в котором расположена страна (классификатор M49 ООН). Источник: http://unstats.un.org/unsd/methods/m49/m49regin.htm.' 
;

COMMENT ON COLUMN DIM_COUNTRY.UN_CONTINENT_NAME IS 'CONTINENT_NAME - континент на котором расположена страна (классификатор M49 ООН). Источник: http://unstats.un.org/unsd/methods/m49/m49regin.htm.' 
;


CREATE TABLE DIM_DAY 
    ( 
     DAY_ID INTEGER  NOT NULL , 
     DAY_DATE DATE  NOT NULL , 
     DAY_OF_WEEK_NAME VARCHAR (16)  NOT NULL , 
     LAST_DAY_IN_WEEK_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_WEEK_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_MONTH_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_MONTH_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_QUARTER_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_QUARTER_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_YEAR_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_YEAR_INDICATOR IN ('No', 'Yes')) , 
     DAY_IN_MONTH_NUMBER SMALLINT  NOT NULL , 
     DAY_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     WEEK_IN_MONTH_NUMBER SMALLINT  NOT NULL , 
     WEEK_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     MONTH_IN_QUARTER_NUMBER SMALLINT  NOT NULL , 
     MONTH_NAME VARCHAR (16)  NOT NULL , 
     QUARTER_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     HALF_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     YEAR_MONTH_NAME VARCHAR (16)  NOT NULL , 
     YEAR_QUARTER_NAME VARCHAR (16)  NOT NULL , 
     YEAR_HALF_NAME VARCHAR (16)  NOT NULL , 
     SEASON_NAME VARCHAR (16)  NOT NULL , 
     WEEKEND_INDICATOR VARCHAR (16)  NOT NULL 
    ) 
;



COMMENT ON TABLE DIM_DAY IS 'DAY - день'
;


COMMENT ON COLUMN DIM_DAY.DAY_ID IS 'DAY_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_DAY.DAY_DATE IS 'DAY_DATE - календарная дата' 
;

COMMENT ON COLUMN DIM_DAY.DAY_OF_WEEK_NAME IS 'DAY_OF_WEEK_NAME - день недели' 
;

COMMENT ON COLUMN DIM_DAY.LAST_DAY_IN_WEEK_INDICATOR IS 'LAST_DAY_IN_WEEK_INDICATOR - признак последнего дня в неделе' 
;

COMMENT ON COLUMN DIM_DAY.LAST_DAY_IN_MONTH_INDICATOR IS 'LAST_DAY_IN_MONTH_INDICATOR - признак последнего дня в месяце' 
;

COMMENT ON COLUMN DIM_DAY.LAST_DAY_IN_QUARTER_INDICATOR IS 'LAST_DAY_IN_QUARTER_INDICATOR - признак последнего дня в квартале' 
;

COMMENT ON COLUMN DIM_DAY.LAST_DAY_IN_YEAR_INDICATOR IS 'LAST_DAY_IN_YEAR_INDICATOR - признак последнего дня в году' 
;

COMMENT ON COLUMN DIM_DAY.DAY_IN_MONTH_NUMBER IS 'DAY_IN_MONTH_NUMBER - день в месяце' 
;

COMMENT ON COLUMN DIM_DAY.DAY_IN_YEAR_NUMBER IS 'DAY_IN_YEAR_NUMBER - день в году' 
;

COMMENT ON COLUMN DIM_DAY.WEEK_IN_MONTH_NUMBER IS 'WEEK_IN_MONTH_NUMBER - неделя в месяце' 
;

COMMENT ON COLUMN DIM_DAY.WEEK_IN_YEAR_NUMBER IS 'WEEK_IN_YEAR_NUMBER - неделя в году' 
;

COMMENT ON COLUMN DIM_DAY.MONTH_IN_QUARTER_NUMBER IS 'MONTH_IN_QUARTER_NUMBER - месяц в квартале' 
;

COMMENT ON COLUMN DIM_DAY.MONTH_NAME IS 'MONTH_NAME - месяц' 
;

COMMENT ON COLUMN DIM_DAY.QUARTER_IN_YEAR_NUMBER IS 'QUARTER_IN_YEAR_NUMBER - квартал в году' 
;

COMMENT ON COLUMN DIM_DAY.HALF_IN_YEAR_NUMBER IS 'HALF_IN_YEAR_NUMBER - половина года' 
;

COMMENT ON COLUMN DIM_DAY.YEAR_MONTH_NAME IS 'YEAR_MONTH_NAME - год и месяц в формате "YYYY-MM"' 
;

COMMENT ON COLUMN DIM_DAY.YEAR_QUARTER_NAME IS 'YEAR_QUARTER_NAME - год и квартал в формате "YYYY-Q"' 
;

COMMENT ON COLUMN DIM_DAY.YEAR_HALF_NAME IS 'YEAR_AND_HALF - год и половина года в формате "YYYY-H"' 
;

COMMENT ON COLUMN DIM_DAY.SEASON_NAME IS 'SEASON_NAME - время года' 
;

COMMENT ON COLUMN DIM_DAY.WEEKEND_INDICATOR IS 'WEEKEND_INDICATOR - признак выходного дня' 
;


CREATE TABLE DIM_DRIVER 
    ( 
     DRIVER_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     FULL_NAME VARCHAR (256)  NOT NULL , 
     BIRTHDAY_PLACE VARCHAR (256)  NOT NULL , 
     INFO VARCHAR (4000) , 
     DEATH_PLACE VARCHAR (256) , 
     BIRTHDAY_ID INTEGER  NOT NULL , 
     COUNTRY_ID INTEGER  NOT NULL , 
     DEATH_DAY_ID INTEGER , 
     PHOTO BLOB 
    ) 
;



COMMENT ON TABLE DIM_DRIVER IS 'DRIVER - гонщик (пилот)'
;


COMMENT ON COLUMN DIM_DRIVER.DRIVER_ID IS 'DRIVER_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_DRIVER.NAME IS 'NAME - имя' 
;

COMMENT ON COLUMN DIM_DRIVER.FULL_NAME IS 'FULL_NAME - полное имя' 
;

COMMENT ON COLUMN DIM_DRIVER.BIRTHDAY_PLACE IS 'BIRTHDAY_PLACE - место рождения' 
;

COMMENT ON COLUMN DIM_DRIVER.INFO IS 'INFO - дополнительная информация' 
;

COMMENT ON COLUMN DIM_DRIVER.DEATH_PLACE IS 'DEATH_PLACE - место смерти' 
;

COMMENT ON COLUMN DIM_DRIVER.BIRTHDAY_ID IS 'BIRTHDAY_ID - дата рождения' 
;

COMMENT ON COLUMN DIM_DRIVER.COUNTRY_ID IS 'COUNTRY_ID - страна, которую представляет гонщик' 
;

COMMENT ON COLUMN DIM_DRIVER.DEATH_DAY_ID IS 'DEATH_DAY_ID - дата смерти (гибели)' 
;

COMMENT ON COLUMN DIM_DRIVER.PHOTO IS 'PHOTO - фотография пилота' 
;


CREATE TABLE DIM_ENGINE 
    ( 
     ENGINE_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     MANUFACTURER VARCHAR (256)  NOT NULL , 
     DEVELOP_DATE DATE  NOT NULL , 
     DISPLACEMENT NUMERIC  NOT NULL , 
     CILINDER_FORMAT VARCHAR (32)  NOT NULL , 
     CHARGE_INDICATOR VARCHAR (3)  NOT NULL CHECK ( CHARGE_INDICATOR IN ('No', 'Yes')) , 
     INFO VARCHAR (256) 
    ) 
;



COMMENT ON TABLE DIM_ENGINE IS 'ENGINE - двигатель гоночного автомобиля'
;


COMMENT ON COLUMN DIM_ENGINE.ENGINE_ID IS 'ENGINE_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_ENGINE.CODE IS 'CODE - кодовое обозначение' 
;

COMMENT ON COLUMN DIM_ENGINE.MANUFACTURER IS 'MANUFACTURER - фирма изготовитель' 
;

COMMENT ON COLUMN DIM_ENGINE.DEVELOP_DATE IS 'DEVELOP_DATE - дата (год) разработки' 
;

COMMENT ON COLUMN DIM_ENGINE.DISPLACEMENT IS 'DISPLACEMENT - объем двигателя' 
;

COMMENT ON COLUMN DIM_ENGINE.CILINDER_FORMAT IS 'FORMAT - формат двигателя (число и расположение цилиндров)' 
;

COMMENT ON COLUMN DIM_ENGINE.CHARGE_INDICATOR IS 'CHARGE_INDICATOR - признак наддувного двигателя' 
;

COMMENT ON COLUMN DIM_ENGINE.INFO IS 'INFO - дополнительная информация' 
;


CREATE TABLE DIM_GRAND_PRIX 
    ( 
     GRAND_PRIX_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     OFFICIAL_NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     TITLE_SPONSOR VARCHAR (256) 
    ) 
;



COMMENT ON TABLE DIM_GRAND_PRIX IS 'GRAND_PRIX - гран при (гоночный уикенд)'
;


COMMENT ON COLUMN DIM_GRAND_PRIX.GRAND_PRIX_ID IS 'GRAND_PRIX_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.CODE IS 'CODE - кодовое обозначение' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.NAME IS 'NAME - наименование' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.OFFICIAL_NAME IS 'OFFICIAL_NAME - официальное наименование гран при' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.YEAR_START IS 'YEAR_START - год (сезон) начала существования гран при в текущей конфигурации' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.YEAR_END IS 'YEAR_END - год (сезон) окончания существования гран при в текущей конфигурации' 
;

COMMENT ON COLUMN DIM_GRAND_PRIX.TITLE_SPONSOR IS 'TITLE_SPONSOR - титульный спонсор гран при' 
;


CREATE TABLE DIM_POSITION_ATTRIBUTES 
    ( 
     POSITION_ATTRIBUTES_ID INTEGER  NOT NULL , 
     RESULT VARCHAR (32) , 
     POSITION SMALLINT , 
     POINTS SMALLINT , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL 
    ) 
;



COMMENT ON TABLE DIM_POSITION_ATTRIBUTES IS 'POSITION_ATTRIBUTES - атрибуты, связанные с позицией пилота на финише гонки'
;


COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.POSITION_ATTRIBUTES_ID IS 'POSITION_ATTRIBUTES_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.RESULT IS 'RESULT - результат гонки' 
;

COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.POSITION IS 'POSITION - позиция финишировавшего и классифицированного пилота на финише' 
;

COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.POINTS IS 'POINTS - количество начисленных очков' 
;

COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.YEAR_START IS 'YEAR_START - с какого года (сезона) действует система начисления очков' 
;

COMMENT ON COLUMN DIM_POSITION_ATTRIBUTES.YEAR_END IS 'YEAR_END - по какой год(сезон) действует система начисления очков' 
;


CREATE TABLE DIM_RACE_ATTRIBUTES 
    ( 
     RACE_ATTRIBUTES_ID INTEGER  NOT NULL , 
     GRID_PENALTY_REASON VARCHAR (256)  NOT NULL , 
     RACE_PENALTY_REASON VARCHAR (32)  NOT NULL , 
     RETIRE_REASON VARCHAR (32)  NOT NULL 
    ) 
;



COMMENT ON TABLE DIM_RACE_ATTRIBUTES IS 'RACE_ATTRIBUTES - различные дополнительные гоночные характеристики'
;


COMMENT ON COLUMN DIM_RACE_ATTRIBUTES.RACE_ATTRIBUTES_ID IS 'RACE_ATTRIBUTES_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_RACE_ATTRIBUTES.GRID_PENALTY_REASON IS 'GRID_PENALTY - причина потери мест на старте' 
;

COMMENT ON COLUMN DIM_RACE_ATTRIBUTES.RACE_PENALTY_REASON IS 'RACE_PENALTY_REASON - причина потери мест на финише' 
;

COMMENT ON COLUMN DIM_RACE_ATTRIBUTES.RETIRE_REASON IS 'RETIRE_REASON - причина схода' 
;


CREATE TABLE DIM_SEASON 
    ( 
     SEASON_ID INTEGER  NOT NULL , 
     YEAR_NUMBER SMALLINT  NOT NULL , 
     LEAP_YEAR_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LEAP_YEAR_INDICATOR IN ('No', 'Yes')) , 
     DECADE VARCHAR (256)  NOT NULL , 
     CENTURY SMALLINT  NOT NULL , 
     ERA VARCHAR (256) 
    ) 
;



COMMENT ON TABLE DIM_SEASON IS 'SEASON - сезон (год) чемпионата'
;


COMMENT ON COLUMN DIM_SEASON.SEASON_ID IS 'SEASON_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_SEASON.YEAR_NUMBER IS 'YEAR_NUMBER - номер года' 
;

COMMENT ON COLUMN DIM_SEASON.LEAP_YEAR_INDICATOR IS 'LEAP_YEAR_INDICATOR - признак високосного года' 
;

COMMENT ON COLUMN DIM_SEASON.DECADE IS 'DECADE - десятилетие' 
;

COMMENT ON COLUMN DIM_SEASON.CENTURY IS 'CENTURY - век' 
;

COMMENT ON COLUMN DIM_SEASON.ERA IS 'ERA - так называемая эра (эпоха) в гонках. Определяется доминирующей технологией' 
;


CREATE TABLE DIM_TEAM 
    ( 
     TEAM_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     FULL_NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     INFO VARCHAR (256) , 
     TITLE_SPONSOR VARCHAR (256) , 
     COUNTRY_ID INTEGER  NOT NULL 
    ) 
;



COMMENT ON TABLE DIM_TEAM IS 'TEAM - команда'
;


COMMENT ON COLUMN DIM_TEAM.TEAM_ID IS 'TEAM_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_TEAM.NAME IS 'NAME - наименование' 
;

COMMENT ON COLUMN DIM_TEAM.FULL_NAME IS 'FULL_NAME - Полное официальное наименование команды' 
;

COMMENT ON COLUMN DIM_TEAM.YEAR_START IS 'YEAR_START - с какого года (сезона) команда выступает в данной конфигурации' 
;

COMMENT ON COLUMN DIM_TEAM.YEAR_END IS 'YEAR_END - по какой год(сезон) команда выступает в данной конфигурации' 
;

COMMENT ON COLUMN DIM_TEAM.INFO IS 'INFO - Дополнительная информация' 
;

COMMENT ON COLUMN DIM_TEAM.TITLE_SPONSOR IS 'TITLE_SPONSOR - титульный спонсор команды' 
;

COMMENT ON COLUMN DIM_TEAM.COUNTRY_ID IS 'COUNTRY_ID - страна за которую выступает команда' 
;


CREATE TABLE DIM_TRACK 
    ( 
     TRACK_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     TURNS SMALLINT  NOT NULL , 
     LENGTH NUMERIC  NOT NULL , 
     COUNTRY_ID INTEGER  NOT NULL , 
     CITY VARCHAR (256)  NOT NULL , 
     REGION VARCHAR (256) , 
     INFO VARCHAR (4000) , 
     SCHEMA BLOB 
    ) 
;



COMMENT ON TABLE DIM_TRACK IS 'TRACK - трасса'
;


COMMENT ON COLUMN DIM_TRACK.TRACK_ID IS 'TRACK_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_TRACK.NAME IS 'NAME - наименование' 
;

COMMENT ON COLUMN DIM_TRACK.YEAR_START IS 'YEAR_START - с какого года (сезона) трасса в данной конфигурации' 
;

COMMENT ON COLUMN DIM_TRACK.YEAR_END IS 'YEAR_END - по какой год(сезон) трасса в данной конфигурации' 
;

COMMENT ON COLUMN DIM_TRACK.TURNS IS 'TURNS - количество поворотов' 
;

COMMENT ON COLUMN DIM_TRACK.LENGTH IS 'LENGTH - длина трассы в конфигурации гран при' 
;

COMMENT ON COLUMN DIM_TRACK.COUNTRY_ID IS 'COUNTRY_ID - страна, на территории которой расположена трасса' 
;

COMMENT ON COLUMN DIM_TRACK.CITY IS 'CITY - город, в котором находится трасса' 
;

COMMENT ON COLUMN DIM_TRACK.REGION IS 'REGION - регион в котором находится трасса ' 
;

COMMENT ON COLUMN DIM_TRACK.INFO IS 'INFO - дополнительная информация' 
;

COMMENT ON COLUMN DIM_TRACK.SCHEMA IS 'SCHEMA - схема трассы' 
;


CREATE TABLE DIM_TYRES 
    ( 
     TYRES_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     INFO VARCHAR (256) , 
     MANUFACTURER VARCHAR (256)  NOT NULL , 
     TREAD VARCHAR (32)  NOT NULL 
    ) 
;



COMMENT ON TABLE DIM_TYRES IS 'TYRES - шины, устанавливаемые на гоночный автомобиль'
;


COMMENT ON COLUMN DIM_TYRES.TYRES_ID IS 'TYRES_ID - суррогатный ключ' 
;

COMMENT ON COLUMN DIM_TYRES.CODE IS 'CODE - кодовое обозначение' 
;

COMMENT ON COLUMN DIM_TYRES.INFO IS 'INFO - дополнительная информация' 
;

COMMENT ON COLUMN DIM_TYRES.MANUFACTURER IS 'MANUFACTURER - фирма изготовитель шин' 
;

COMMENT ON COLUMN DIM_TYRES.TREAD IS 'TREAD - тип протектора' 
;


CREATE TABLE FACT_GRAND_PRIX_RESULTS 
    ( 
     DRIVER_NUMBER SMALLINT , 
     START_POSITION SMALLINT , 
     QUALIFYING_POSITION SMALLINT , 
     FINISH_TIME TIMESTAMP , 
     AVERAGE_SPEED NUMERIC , 
     FASTEST_LAP_TIME TIMESTAMP , 
     LAPS_IN_RACE SMALLINT , 
     LAPS_PASSED SMALLINT , 
     HALF_POINTS_INDICATOR NUMERIC , 
     RACE_DAY_ID INTEGER  NOT NULL , 
     DRIVER_ID INTEGER  NOT NULL , 
     EAM_ID INTEGER  NOT NULL , 
     TRACK_ID INTEGER  NOT NULL , 
     CHASSIS_ID INTEGER  NOT NULL , 
     ENGINE_ID INTEGER  NOT NULL , 
     SEASON_ID INTEGER  NOT NULL , 
     GRAND_PRIX_ID INTEGER  NOT NULL , 
     RACE_ATTRIBUTES_ID INTEGER  NOT NULL , 
     TYRES_ID INTEGER  NOT NULL , 
     POSITION_ATTRIBUTES_ID INTEGER  NOT NULL 
    ) 
;



COMMENT ON TABLE FACT_GRAND_PRIX_RESULTS IS 'GRAND_PRIX_RESULTS - результаты гран при с детализацией до гонщика'
;


COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.DRIVER_NUMBER IS 'DRIVER_NUMBER - номер гонщика в чемпионате' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.START_POSITION IS 'START_POSITION - стартовая позиция гонщика' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.QUALIFYING_POSITION IS 'QUALIFYING_POSITION - позиция гонщика, показанная в квалификации' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.FINISH_TIME IS 'FINISH_TIME - время на финише' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.AVERAGE_SPEED IS 'AVERAGE_SPEED - средняя скорость' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.FASTEST_LAP_TIME IS 'FASTEST_LAP_TIME - время бысрейшего круга в гонке' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.LAPS_IN_RACE IS 'LAPS_IN_RACE - запланированное количество кругов в гонке' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.LAPS_PASSED IS 'LAPS_PASSED - количество пройденных пилотом кругов' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.HALF_POINTS_INDICATOR IS 'HALF_POINTS_INDICATOR - признак того, что за гонку начислили половину очков' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.RACE_DAY_ID IS 'RACE_DAY_ID - дата гонки' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.DRIVER_ID IS 'DRIVER_ID - гонщик' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.EAM_ID IS 'TEAM_ID - команда, за которую выступает гонщик' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.TRACK_ID IS 'TRACK_ID - трасса, где проходит гран при' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.CHASSIS_ID IS 'CHASSIS_ID - шасси, на котором выступает гонщик' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.ENGINE_ID IS 'ENGINE_ID - двигатель гоночного автомобиля' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.SEASON_ID IS 'SEASON_ID - сезон проведения гран при' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.GRAND_PRIX_ID IS 'GRAND_PRIX_ID - гран при' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.RACE_ATTRIBUTES_ID IS 'RACE_ATTRIBUTES_ID - различные атрибуты' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.TYRES_ID IS 'TYRES_ID - шины гоночного автомобиля' 
;

COMMENT ON COLUMN FACT_GRAND_PRIX_RESULTS.POSITION_ATTRIBUTES_ID IS 'POSITION_ATTRIBUTES_ID - атрибуты итогов гонки' 
;
