CREATE TABLE DIM_CHASSIS 
    ( 
     CHASSIS_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     CONSTRUCTOR VARCHAR (256) , 
     DEVELOP_DATE DATE , 
     INFO VARCHAR (256) 
    ) 

COMMENT 'CHASSIS - шасси гоночного автомобиля';






CREATE TABLE DIM_COUNTRY 
    ( 
     COUNTRY_ID INTEGER  NOT NULL , 
     SCD_START DATE  NOT NULL , 
     SCD_END DATE  NOT NULL , 
     SCD_ACTIVE NUMERIC DEFAULT 1  NOT NULL , 
     SCD_VERSION SMALLINT  NOT NULL , 
     NUMERIC_CODE VARCHAR (3)  NOT NULL , 
     ALPHA_CODE VARCHAR (3) , 
     COUNTRY_NAME VARCHAR (256) , 
     SHORT_NAME VARCHAR (256) , 
     UN_REGION_NAME VARCHAR (256) , 
     UN_CONTINENT_NAME VARCHAR (256) 
    ) 

COMMENT 'COUNTRY - страна';












CREATE TABLE DIM_DAY 
    ( 
     DAY_ID INTEGER  NOT NULL , 
     DAY_DATE DATE  NOT NULL , 
     DAY_OF_WEEK_NAME VARCHAR (16)  NOT NULL , 
     LAST_DAY_IN_WEEK_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_WEEK_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_MONTH_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_MONTH_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_QUARTER_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_QUARTER_INDICATOR IN ('No', 'Yes')) , 
     LAST_DAY_IN_YEAR_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LAST_DAY_IN_YEAR_INDICATOR IN ('No', 'Yes')) , 
     DAY_IN_MONTH_NUMBER SMALLINT  NOT NULL , 
     DAY_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     WEEK_IN_MONTH_NUMBER SMALLINT  NOT NULL , 
     WEEK_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     MONTH_IN_QUARTER_NUMBER SMALLINT  NOT NULL , 
     MONTH_NAME VARCHAR (16)  NOT NULL , 
     QUARTER_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     HALF_IN_YEAR_NUMBER SMALLINT  NOT NULL , 
     YEAR_MONTH_NAME VARCHAR (16)  NOT NULL , 
     YEAR_QUARTER_NAME VARCHAR (16)  NOT NULL , 
     YEAR_HALF_NAME VARCHAR (16)  NOT NULL , 
     SEASON_NAME VARCHAR (16)  NOT NULL , 
     WEEKEND_INDICATOR VARCHAR (16)  NOT NULL 
    ) 

COMMENT 'DAY - день';





















CREATE TABLE DIM_DRIVER 
    ( 
     DRIVER_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     FULL_NAME VARCHAR (256)  NOT NULL , 
     BIRTHDAY_PLACE VARCHAR (256)  NOT NULL , 
     INFO VARCHAR (4000) , 
     DEATH_PLACE VARCHAR (256) , 
     BIRTHDAY_ID INTEGER  NOT NULL , 
     COUNTRY_ID INTEGER  NOT NULL , 
     DEATH_DAY_ID INTEGER , 
     PHOTO BLOB 
    ) 

COMMENT 'DRIVER - гонщик (пилот)';











CREATE TABLE DIM_ENGINE 
    ( 
     ENGINE_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     MANUFACTURER VARCHAR (256)  NOT NULL , 
     DEVELOP_DATE DATE  NOT NULL , 
     DISPLACEMENT NUMERIC  NOT NULL , 
     CILINDER_FORMAT VARCHAR (32)  NOT NULL , 
     CHARGE_INDICATOR VARCHAR (3)  NOT NULL CHECK ( CHARGE_INDICATOR IN ('No', 'Yes')) , 
     INFO VARCHAR (256) 
    ) 

COMMENT 'ENGINE - двигатель гоночного автомобиля';









CREATE TABLE DIM_GRAND_PRIX 
    ( 
     GRAND_PRIX_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     OFFICIAL_NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     TITLE_SPONSOR VARCHAR (256) 
    ) 

COMMENT 'GRAND_PRIX - гран при (гоночный уикенд)';








CREATE TABLE DIM_POSITION_ATTRIBUTES 
    ( 
     POSITION_ATTRIBUTES_ID INTEGER  NOT NULL , 
     RESULT VARCHAR (32) , 
     POSITION SMALLINT , 
     POINTS SMALLINT , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL 
    ) 

COMMENT 'POSITION_ATTRIBUTES - атрибуты, связанные с позицией пилота на финише гонки';







CREATE TABLE DIM_RACE_ATTRIBUTES 
    ( 
     RACE_ATTRIBUTES_ID INTEGER  NOT NULL , 
     GRID_PENALTY_REASON VARCHAR (256)  NOT NULL , 
     RACE_PENALTY_REASON VARCHAR (32)  NOT NULL , 
     RETIRE_REASON VARCHAR (32)  NOT NULL 
    ) 

COMMENT 'RACE_ATTRIBUTES - различные дополнительные гоночные характеристики';





CREATE TABLE DIM_SEASON 
    ( 
     SEASON_ID INTEGER  NOT NULL , 
     YEAR_NUMBER SMALLINT  NOT NULL , 
     LEAP_YEAR_INDICATOR VARCHAR (3)  NOT NULL CHECK ( LEAP_YEAR_INDICATOR IN ('No', 'Yes')) , 
     DECADE VARCHAR (256)  NOT NULL , 
     CENTURY SMALLINT  NOT NULL , 
     ERA VARCHAR (256) 
    ) 

COMMENT 'SEASON - сезон (год) чемпионата';







CREATE TABLE DIM_TEAM 
    ( 
     TEAM_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     FULL_NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     INFO VARCHAR (256) , 
     TITLE_SPONSOR VARCHAR (256) , 
     COUNTRY_ID INTEGER  NOT NULL 
    ) 

COMMENT 'TEAM - команда';









CREATE TABLE DIM_TRACK 
    ( 
     TRACK_ID INTEGER  NOT NULL , 
     NAME VARCHAR (256)  NOT NULL , 
     YEAR_START SMALLINT  NOT NULL , 
     YEAR_END SMALLINT  NOT NULL , 
     TURNS SMALLINT  NOT NULL , 
     LENGTH NUMERIC  NOT NULL , 
     COUNTRY_ID INTEGER  NOT NULL , 
     CITY VARCHAR (256)  NOT NULL , 
     REGION VARCHAR (256) , 
     INFO VARCHAR (4000) , 
     SCHEMA BLOB 
    ) 

COMMENT 'TRACK - трасса';












CREATE TABLE DIM_TYRES 
    ( 
     TYRES_ID INTEGER  NOT NULL , 
     CODE VARCHAR (32)  NOT NULL , 
     INFO VARCHAR (256) , 
     MANUFACTURER VARCHAR (256)  NOT NULL , 
     TREAD VARCHAR (32)  NOT NULL 
    ) 

COMMENT 'TYRES - шины, устанавливаемые на гоночный автомобиль';






CREATE TABLE FACT_GRAND_PRIX_RESULTS 
    ( 
     DRIVER_NUMBER SMALLINT , 
     START_POSITION SMALLINT , 
     QUALIFYING_POSITION SMALLINT , 
     FINISH_TIME TIMESTAMP , 
     AVERAGE_SPEED NUMERIC , 
     FASTEST_LAP_TIME TIMESTAMP , 
     LAPS_IN_RACE SMALLINT , 
     LAPS_PASSED SMALLINT , 
     HALF_POINTS_INDICATOR NUMERIC , 
     RACE_DAY_ID INTEGER  NOT NULL , 
     DRIVER_ID INTEGER  NOT NULL , 
     EAM_ID INTEGER  NOT NULL , 
     TRACK_ID INTEGER  NOT NULL , 
     CHASSIS_ID INTEGER  NOT NULL , 
     ENGINE_ID INTEGER  NOT NULL , 
     SEASON_ID INTEGER  NOT NULL , 
     GRAND_PRIX_ID INTEGER  NOT NULL , 
     RACE_ATTRIBUTES_ID INTEGER  NOT NULL , 
     TYRES_ID INTEGER  NOT NULL , 
     POSITION_ATTRIBUTES_ID INTEGER  NOT NULL 
    ) 

COMMENT 'GRAND_PRIX_RESULTS - результаты гран при с детализацией до гонщика';





















